using FlowDesk.Domain.Common;
using FlowDesk.Domain.Tenancy;

namespace FlowDesk.Domain.Tickets;

/// <summary>
/// A file attached to a ticket.
/// </summary>
/// <remarks>
/// The row is the record; the bytes live in object storage under
/// <see cref="StorageKey"/>. Splitting them means an attachment can be
/// authorised, listed and removed through the database alone, and the storage
/// service never needs to know who may read what.
/// </remarks>
public sealed class Attachment : ITenantOwned
{
    public const int MaximumFileNameLength = 255;
    public const int MaximumContentTypeLength = 100;

    private Attachment()
    {
        FileName = string.Empty;
        ContentType = string.Empty;
        StorageKey = string.Empty;
    }

    private Attachment(
        Guid id,
        Guid tenantId,
        Guid ticketId,
        string fileName,
        string contentType,
        long sizeInBytes,
        string storageKey,
        Guid uploadedByUserId,
        DateTimeOffset createdAt)
    {
        Id = id;
        TenantId = tenantId;
        TicketId = ticketId;
        FileName = fileName;
        ContentType = contentType;
        SizeInBytes = sizeInBytes;
        StorageKey = storageKey;
        UploadedByUserId = uploadedByUserId;
        CreatedAt = createdAt;
    }

    public Guid Id { get; private set; }

    public Guid TenantId { get; private set; }

    public Guid TicketId { get; private set; }

    /// <summary>
    /// The name shown to people, already cleaned.
    /// </summary>
    /// <remarks>
    /// Display only. It is never used to build a path: the bytes are addressed
    /// by <see cref="StorageKey"/>, which the server generates.
    /// </remarks>
    public string FileName { get; private set; }

    public string ContentType { get; private set; }

    public long SizeInBytes { get; private set; }

    /// <summary>
    /// Where the bytes are, generated by the server.
    /// </summary>
    /// <remarks>
    /// Contains the workspace id, so even a mistake in the authorisation layer
    /// leaves one organisation's files in a different prefix from another's
    /// (ADR-0035).
    /// </remarks>
    public string StorageKey { get; private set; }

    public Guid UploadedByUserId { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public static Attachment Create(
        Guid tenantId,
        Guid ticketId,
        string fileName,
        string contentType,
        long sizeInBytes,
        string storageKey,
        Guid uploadedByUserId,
        DateTimeOffset createdAt)
    {
        if (tenantId == Guid.Empty)
        {
            throw new DomainRuleViolationException("An attachment must belong to a workspace.");
        }

        if (ticketId == Guid.Empty)
        {
            throw new DomainRuleViolationException("An attachment must belong to a ticket.");
        }

        if (uploadedByUserId == Guid.Empty)
        {
            throw new DomainRuleViolationException("An attachment must record who uploaded it.");
        }

        if (sizeInBytes <= 0)
        {
            // An empty file is not a file. Accepting one would leave a row
            // pointing at nothing and a download that returns no bytes.
            throw new DomainRuleViolationException("An attachment cannot be empty.");
        }

        return new Attachment(
            Guid.CreateVersion7(),
            tenantId,
            ticketId,
            Require(fileName, MaximumFileNameLength, "file name"),
            Require(contentType, MaximumContentTypeLength, "content type"),
            sizeInBytes,
            Require(storageKey, 512, "storage key"),
            uploadedByUserId,
            createdAt);
    }

    private static string Require(string? value, int maximumLength, string fieldName)
    {
        var trimmed = (value ?? string.Empty).Trim();

        if (trimmed.Length == 0)
        {
            throw new DomainRuleViolationException($"An attachment must have a {fieldName}.");
        }

        if (trimmed.Length > maximumLength)
        {
            throw new DomainRuleViolationException(
                $"An attachment {fieldName} cannot exceed {maximumLength} characters.");
        }

        return trimmed;
    }
}
